package-lock.json, package.json, schema/schema.sql
Equipo tomen en cuenta que el schema tiene un DROP DATABASE. 
close #5
=> Se agrega schema de DB, y se inicializa proyecto con paquetes iniciales

models/DevicePackage.js, models/Hardware.js, models/Provider.js, models/Software.js, models/User.js, models/index.js
Closes #8 
Closes #9 
Closes #10 
Closes #11 
Closes #12
=> Se agrega reestructuracion de modelos

config/connection.js
=> se agrega conecciones a base de datos

package-lock.json, package.json, server.js
=> se agrega archivo server.js

controllers/api/deviceRoutes.js, controllers/api/index.js, controllers/api/providerRoutes.js, controllers/api/userRoutes.js, models/Hardware.js, models/Software.js
=>  se soluciona syn force de sequelize issue 36

controllers/homeRoutes.js, controllers/index.js, views/index.handlebars, views/layouts/main.handlebars, views/partials/messages.handlebars, views/partials/navigation.handlebars
Closes issue #38 
Closes issue #39
=>  se resulven issues #38 y #39

controllers/api/userRoutes.js
=>  Se agregan y testean  rutas de usuario

controllers/api/userRoutes.js, controllers/homeRoutes.js, views/login.handlebars, views/partials/navigation.handlebars
=>  se agrega vista de login y se agregar a ruta de menu

controllers/api/userRoutes.js, models/User.js
=>  se agrega busqueda y registro de usuario issue #18

controllers/api/deviceRoutes.js
=> se agrega endpoint de devicepackage

controllers/api/userRoutes.js, controllers/homeRoutes.js, server.js
=> se agrega registro, se resuelve issue#46

controllers/api/userRoutes.js
=> se agrega eliminar sesion

controllers/api/providerRoutes.js, utils/appAuth.js, views/partials/navigation.handlebars
=> se agrega middleware de autorizacion, se testea en endpoint providers

controllers/api/providerRoutes.js
closes #22 
closes #23 
closes #24 
closes #25
=> Se agregan rutas de proveedores.

models/Provider.js
=> Se realizan modificaciones en el modelo de Proveedores.

package-lock.json, package.json, public/js/Provider.js, server.js, views/layouts/main.handlebars
se corrige provider.js, se corrige main page eliminando css inexistente e innecesario para este proyecto.
close #62
=> se implementa morgan middleware

controllers/api/softwareRoutes.js
=> se agregan cambios en rutas para completar modelo MVC

models/Software.js, views/partials/navigation.handlebars
=> se agregan cambios en archivo navigation y en modelo de software

controllers/api/hardwareRoutes.js
Closes issue #72 
Closes issue #73
=> se agrega correccion de rutas get y se agrega autenticacion

controllers/api/hardwareRoutes.js
=> se corrige ruta POST

controllers/api/hardwareRoutes.js
=> se corrige ruta PUT

controllers/api/hardwareRoutes.js
=> Se corrige ruta DELETE

views/partials/listhardware.handlebars
=> Se agrega handlebars de lista de hardware

views/hardware.handlebars, views/hardwarepage.handlebars
=> se agrega handlebars de hardware

views/software.handlebars, views/softwarepage.handlebars
=> se agregan archivos handlebars de modulo de software en vistas

controllers/api/softwareRoutes.js, views/softwarepage.handlebars
=> se agregan modificaciones a despliegue de software

controllers/api/providerRoutes.js
=> se agrega autenticacion de rutas proveedor

views/index.handlebars
=> Se corrige descripcion de pa pagina home

controllers/api/providerRoutes.js
Reverts carlosgortiz/tech-inventory-web-app#94
=> Revert "se agrega autenticacion de rutas proveedor"

controllers/api/providerRoutes.js
Reverts carlosgortiz/tech-inventory-web-app#97
=> Revert "Revert "se agrega autenticacion de rutas proveedor""

views/partials/navigation.handlebars
=> se corrige css de barra de navegacion
